# Generated by Django 4.2.7 on 2023-11-16 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total', models.FloatField()),
                ('estatus', models.CharField(choices=[('procesando', 'En proceso'), ('cancelada', 'Cancelada'), ('entregada', 'Entregada'), ('pagada', 'Pagada')], default='Procesando', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Iva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('porcentaje', models.IntegerField()),
                ('validez', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('marca', models.CharField(max_length=20)),
                ('descripcion', models.TextField(default='Sin descripcion')),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('RFC', models.CharField(max_length=12)),
                ('estatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Talla_Producto',
            fields=[
                ('talla', models.CharField(choices=[('CH', 'CH'), ('M', 'M'), ('L', 'L')], max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nombre_usuario', models.CharField(max_length=18)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('empleado', 'Empleado'), ('cliente', 'Cliente')], default='Administrador', max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('contrasenia', models.CharField(max_length=18)),
                ('estatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total', models.FloatField()),
                ('estatus', models.CharField(choices=[('procesando', 'En proceso'), ('cancelada', 'Cancelada'), ('en_camino', 'En transito'), ('entregada', 'Entregada'), ('pagada', 'Pagada')], max_length=20)),
                ('IDCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='VentaProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField()),
                ('IDProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_api.producto')),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_api.venta')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='talla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_api.talla_producto'),
        ),
        migrations.CreateModel(
            name='Compra_Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField()),
                ('IDProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_api.producto')),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_api.compra')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='IDProveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_api.proveedor'),
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_minimo', models.IntegerField(default=1)),
                ('stock_maximo', models.IntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_api.producto')),
            ],
        ),
    ]
