# Generated by Django 4.2.7 on 2023-11-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='stock_actual',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(verbose_name='fecha'),
        ),
    ]
