# Generated by Django 4.2.7 on 2023-11-17 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_api', '0003_alter_compra_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='almacen',
            old_name='producto',
            new_name='IDproducto',
        ),
        migrations.AlterField(
            model_name='almacen',
            name='stock_maximo',
            field=models.IntegerField(default=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_api.proveedor'),
        ),
    ]
