# Generated by Django 4.2.7 on 2023-11-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_api', '0005_alter_producto_options_producto_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='almacen',
            options={'verbose_name': 'almacen', 'verbose_name_plural': 'almacen'},
        ),
        migrations.AlterModelOptions(
            name='iva',
            options={'verbose_name': 'IVA', 'verbose_name_plural': 'IVAs'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'proveedor', 'verbose_name_plural': 'proveedores'},
        ),
        migrations.AddField(
            model_name='producto',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='producto'),
        ),
    ]
