# Generated by Django 4.2.7 on 2023-11-28 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_api', '0006_alter_almacen_options_alter_iva_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='total',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='total',
        ),
        migrations.AlterField(
            model_name='almacen',
            name='stock_actual',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=255)]),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='stock_maximo',
            field=models.PositiveSmallIntegerField(default=255, validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='stock_minimo',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
    ]
