# Generated by Django 4.2.7 on 2023-11-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_api', '0007_remove_compra_total_remove_venta_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'verbose_name': 'compra', 'verbose_name_plural': 'compras'},
        ),
        migrations.AlterModelOptions(
            name='compra_productos',
            options={'verbose_name': 'compra_producto', 'verbose_name_plural': 'compras_productos'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name': 'venta', 'verbose_name_plural': 'ventas'},
        ),
        migrations.AlterModelOptions(
            name='ventaproductos',
            options={'verbose_name': 'venta_producto', 'verbose_name_plural': 'ventas_productos'},
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='iva',
            name='validez',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='almacen',
            table='stock',
        ),
        migrations.AlterModelTable(
            name='compra',
            table='compras',
        ),
        migrations.AlterModelTable(
            name='compra_productos',
            table='compras_productos',
        ),
        migrations.AlterModelTable(
            name='iva',
            table='IVA',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='productos',
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='proveedores',
        ),
        migrations.AlterModelTable(
            name='talla_producto',
            table='tallas',
        ),
        migrations.AlterModelTable(
            name='venta',
            table='ventas',
        ),
        migrations.AlterModelTable(
            name='ventaproductos',
            table='ventas_productos',
        ),
    ]
