# Generated by Django 4.2.7 on 2023-11-29 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_api', '0008_alter_compra_options_alter_compra_productos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='compra',
            table=None,
        ),
    ]
