# Generated by Django 4.2.7 on 2023-11-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_api', '0009_alter_compra_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estatus',
            field=models.CharField(choices=[('procesando', 'En proceso'), ('cancelada', 'Cancelada'), ('entregada', 'Entregada'), ('pagada', 'Pagada')], default='procesando', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estatus',
            field=models.CharField(choices=[('procesando', 'procesando'), ('cancelada', 'Cancelada'), ('en_camino', 'En transito'), ('entregada', 'Entregada'), ('pagada', 'Pagada')], default='procesando', max_length=20),
        ),
    ]
