# Generated by Django 4.2.7 on 2023-12-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_api', '0010_alter_compra_estatus_alter_venta_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estatus',
            field=models.CharField(choices=[('procesando', 'En proceso'), ('cancelada', 'Cancelada'), ('entregada', 'Entregada'), ('pagada', 'Pagada')], default='entregada', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estatus',
            field=models.CharField(choices=[('procesando', 'procesando'), ('cancelada', 'Cancelada'), ('pagada', 'Pagada'), ('En camino', 'En transito'), ('entregada', 'Entregada')], default='pagada', max_length=20),
        ),
    ]
