# Generated by Django 4.2.7 on 2023-12-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_api', '0011_alter_compra_estatus_alter_venta_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estatus',
            field=models.CharField(choices=[('Procesando', 'procesando'), ('cancelada', 'Cancelada'), ('En camino', 'En transito'), ('entregada', 'Entregada')], default='pagada', max_length=20),
        ),
    ]
