# Generated by Django 4.2.7 on 2023-12-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_api', '0013_alter_compra_estatus_alter_venta_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estatus',
            field=models.CharField(choices=[('Cancelada', 'Cancelada'), ('Entregada', 'Entregada'), ('Pagada', 'Pagada')], default='entregada', max_length=20),
        ),
    ]
